#!/bin/sh

source ./PKGBUILD
PKGVER="${pkgver}"

DKRVER=$(sh ./docker/tomato.sh version number 2> /dev/null)
TMTVER=$(sh ./tomato -VV 2> /dev/null)
RDMVER=$(grep -s -h -o 'Tomato v[0-9.]\+' ./README.md | sed 's:Tomato v::')

ret=0


if test "${PKGVER}" != "${TMTVER}";
then
	echo "Invalid package version ${PKGVER}, should be ${TMTVER}" 1>&2
	ret=1
fi

if test "${DKRVER}" != "${TMTVER}";
then
	echo "Invalid scripts versions ${TMTVER} != ${DKRVER}" 1>&2
	ret=1
fi

if test "${RDMVER}" != "${TMTVER}";
then
	echo "Invalid README versions ${RDMVER} != ${TMTVER}" 1>&2
	ret=1
fi

if test $ret -eq 0;
then
	echo "$PKGVER"
else
	cat 1>&2 <<EOF
Package: ${PKGVER}
Host   : ${TMTVER}
Docker : ${DKRVER}
README : ${RDMVER}
EOF
fi

exit $ret
