#!/bin/sh

source ./PKGBUILD
PKGVER="${pkgver}"

DKRVER=$(sh ./docker/tomato.sh version number)
TMTVER=$(sh ./tomato -VV)

ret=0


if test "${PKGVER}" != "${TMTVER}";
then
	echo "Invalid package version ${PKGVER}, should be ${TMTVER}" 1>&2
	ret=1
fi

if test "${DKRVER}" != "${TMTVER}";
then
	echo "Invalid scripts versions ${TMTVER} != ${DKRVER}" 1>&2
	ret=1
fi

if test $ret -eq 0;
then
	echo "$PKGVER"
else
	cat 1>&2 <<EOF
Package: ${PKGVER}
Host   : ${TMTVER}
Docker : ${DKRVER}
EOF
fi

exit $ret
